spring:
  application.name: beer-api-consumer
  # remove::start[]
  cloud.stream.bindings.input-in-0.destination: verifications
  # remove::end[]

beer-api-producer-restdocs:
  url: http://localhost:8081

logging:
  level:
    org.springframework.cloud: debug